/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    final static int maxRandomNumber = 4;// ランダムな数値の最大値(0～4)

    public String getGreeting() {
        return "Hello SeMonster!";
    }
    // test
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        SeMonsterGame game = new SeMonsterGame(maxRandomNumber);
        game.addPlayer("hoge", 3);
        game.addPlayer("fuga", 3);
        game.showAllPlayersDeck();
    }
}